### ISSUE TITLE
Can you provide an example how this package can be used for a regression or classification problem?

### ISSUE THREAD

**Issue by rt3722** [suren-rathnayake/deepgmm#1]

**Comment by suren-rathnayake** [comment]
The purpose of this package is to cluster data.

**Comment by rt3722** [comment]
just figured it out.
Thank you.

**Comment by rt3722** [comment]
Do you know what this error message means 
Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)

**Comment by suren-rathnayake** [comment]
Do you have characters etc in your data? For _deepgmm_ (as in k-means) you have to have only numerical values in your data.

**Comment by rt3722** [comment]
Thank you.
